/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Bonificaciones.java
 *
 * Created on 07-dic-2012, 9:53:40
 */
package com.gestionmatriz.recursoshumanos.gui;

import java.math.BigDecimal;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import com.gestionmatriz.dao.PaqueteBusinessDelegate;
import com.gestionmatriz.principal.gui.Principal;
import com.gestionmatriz.recursoshumanos.bean.Bonificacion;
import com.gestionmatriz.util.Mensaje;
import com.gestionmatriz.util.Util;
/**
 *
 * @author zholo
 */
public class Bonificaciones extends javax.swing.JInternalFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	Principal gui;
    
    Bonificacion objBonificacion=null;
    /** Creates new form Bonificaciones */
    public Bonificaciones(Principal gui) {
        this.gui=gui;
        initComponents();
        cargarTabla(PaqueteBusinessDelegate.getBonificacionService().listaBonificacion());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBonificacion = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Crear Bonificación");

        jLabel1.setText("Descripción :");

        jLabel2.setText("Monto S/. :");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnDeshabilitar.setText("Deshabilitar");
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });

        tblBonificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBonificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBonificacionMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblBonificacion);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnRegistrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeshabilitar)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnDeshabilitar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    
    Bonificacion objBonificacion=new Bonificacion();
    
    objBonificacion.setStr_descripcion(txtDescripcion.getText().trim());
    objBonificacion.setDbl_monto(new BigDecimal(txtMonto.getText().trim()));
    objBonificacion.setStr_usuarioCreador(gui.getBarraEstado().getUsuario());
    
    if(PaqueteBusinessDelegate.getBonificacionService().registrarBonifiacion(objBonificacion)==true){
        Mensaje.mensaje("Registro correcto", Mensaje.TITULO_ME, Mensaje.INFORMACION);
        cargarTabla(PaqueteBusinessDelegate.getBonificacionService().listaBonificacion());
    }else{
        Mensaje.mensaje("Error en registro de bonificación", Mensaje.TITULO_ME, Mensaje.ERROR);
    }
    
}//GEN-LAST:event_btnRegistrarActionPerformed

private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    if(objBonificacion==null){
        Mensaje.mensaje("Debe seleccionar una opción de la tabla", Mensaje.TITULO_ME, Mensaje.ERROR);
        return;
    }
       
    objBonificacion.setStr_descripcion(txtDescripcion.getText().trim());
    objBonificacion.setDbl_monto(new BigDecimal(txtMonto.getText().trim()));
    objBonificacion.setStr_estado(Util.ACTIVO);
    objBonificacion.setStr_usuarioCreador(gui.getBarraEstado().getUsuario());
    
    
    if(PaqueteBusinessDelegate.getBonificacionService().modificarBonifiacion(objBonificacion)==true){
        Mensaje.mensaje("Modificacion correcta", Mensaje.TITULO_ME, Mensaje.INFORMACION);
        cargarTabla(PaqueteBusinessDelegate.getBonificacionService().listaBonificacion());
        limpiar();
    }else{
        Mensaje.mensaje("Error al modificar los datos", Mensaje.TITULO_ME, Mensaje.ERROR);
    }
    
}//GEN-LAST:event_btnModificarActionPerformed

private void tblBonificacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBonificacionMousePressed
    
    int index =tblBonificacion.getSelectedRow();
    List<Bonificacion>lista=PaqueteBusinessDelegate.getBonificacionService().listaBonificacion();
    if(index<0){
        return;
    }
//    System.out.println("indice ---"+index);
    objBonificacion= lista.get(index);
//    System.out.println("id---"+objBonificacion.getInt_idBonificacion());
    
    txtDescripcion.setText(objBonificacion.getStr_descripcion());
    txtMonto.setText(""+objBonificacion.getDbl_monto());
    if(objBonificacion.getStr_estado().equalsIgnoreCase("INACTIVO")){
        btnDeshabilitar.setText("Habilitar");
    }else{
        btnDeshabilitar.setText("Deshabilitar");
    }
}//GEN-LAST:event_tblBonificacionMousePressed

private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
    
    if(objBonificacion==null){
        Mensaje.mensaje("Debe seleccionar una opción de la tabla", Mensaje.TITULO_ME, Mensaje.ERROR);
        return;
    }
//    objBonificacion.setStr_descripcion(txtDescripcion.getText().trim());
//    objBonificacion.setDbl_monto(BigDecimal.parseBigDecimal(txtMonto.getText().trim()));
    if(btnDeshabilitar.getText().equalsIgnoreCase("Deshabilitar")){
        objBonificacion.setStr_estado(Util.INACTIVO);
    }else{
        objBonificacion.setStr_estado(Util.ACTIVO);
    }
    
    objBonificacion.setStr_usuarioCreador(gui.getBarraEstado().getUsuario());
    
    if(PaqueteBusinessDelegate.getBonificacionService().modificarBonifiacion(objBonificacion)==true){
        Mensaje.mensaje("Modificacion correcta", Mensaje.TITULO_ME, Mensaje.INFORMACION);
        cargarTabla(PaqueteBusinessDelegate.getBonificacionService().listaBonificacion());
        limpiar();
    }else {
        Mensaje.mensaje("Error al modificar los datos", Mensaje.TITULO_ME, Mensaje.ERROR);
    
    }
}//GEN-LAST:event_btnDeshabilitarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBonificacion;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

private void cargarTabla(List<Bonificacion> listaBonificacion) {
        String[] titulo = {"Código","Descripción","Monto","Estado"};
        String[][] data = new String[listaBonificacion.size()][4];
        int i = 0;
        //recorro la lista de especialidades 
        for (Bonificacion e : listaBonificacion) {
            //asigno los valores de del objeto a los campos de la tablas
            data[i][0] = ""+e.getInt_idBonificacion();            
            data[i][1] = e.getStr_descripcion();
            data[i][2] = ""+e.getDbl_monto();
            data[i][3] = e.getStr_estado();
                       
            i++;
        }
        //muestro los valores en la tabla
        DefaultTableModel modelo = new DefaultTableModel(data, titulo);
        tblBonificacion.setModel(modelo);
    }

    public void limpiar(){
        txtDescripcion.setText("");
        txtMonto.setText("");
        objBonificacion=null;
    }

}
