/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MarcadoUsuario.java
 *
 * Created on 19-dic-2012, 0:08:37
 */
package com.gestionmatriz.recursoshumanos.servicio;

import com.gestionmatriz.dao.PaqueteBusinessDelegate;
import com.gestionmatriz.recursoshumanos.bean.HorarioJornadaContrato;
import com.gestionmatriz.recursoshumanos.gui.Marcado;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author zholo
 */
public class MarcadoUsuario extends JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form MarcadoUsuario */
    
    private HorarioJornadaContrato objHorarioJornadaContrato;
    private Marcado frmMarcado;
    private boolean tipoMarcado;

    public boolean isTipoMarcado() {
        return tipoMarcado;
    }

    public void setTipoMarcado(boolean tipoMarcado) {
        this.tipoMarcado = tipoMarcado;
    }
    
    
    
    public MarcadoUsuario(JFrame guiF,Marcado frmMarcado,boolean tipoMarcado) {
        super(guiF,true);
        this.setTitle("Marcado por Usuario - Contraseña");
        this.frmMarcado=frmMarcado;
        this.tipoMarcado=tipoMarcado;
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        lblUsuario = new org.jdesktop.swingx.JXLabel();
        txtUsuario = new org.jdesktop.swingx.JXTextField();
        lblPassword = new org.jdesktop.swingx.JXLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnMarcar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setType(java.awt.Window.Type.UTILITY);

        lblUsuario.setText("Usuario: ");

        lblPassword.setText("Password: ");

        btnMarcar.setText("Marcar");
        btnMarcar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

private void btnMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarActionPerformed
    objHorarioJornadaContrato=PaqueteBusinessDelegate.getAsistenciaService().registrarAsistencia
            (txtUsuario.getText(), new String(txtPassword.getPassword()), tipoMarcado);
    if (objHorarioJornadaContrato!=null){
        frmMarcado.setObjHorarioJornadaContrato(objHorarioJornadaContrato);
        txtUsuario.setText("");
        txtPassword.setText("");
        txtUsuario.requestFocus();
    }
    else
    {
        frmMarcado.setObjHorarioJornadaContrato(null);
        txtUsuario.setText("");
        txtPassword.setText("");
        txtUsuario.requestFocus();
    }
    this.setVisible(false);
}//GEN-LAST:event_btnMarcarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMarcar;
    private org.jdesktop.swingx.JXLabel lblPassword;
    private org.jdesktop.swingx.JXLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private org.jdesktop.swingx.JXTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
