/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportePersona.java
 *
 * Created on 14-may-2012, 11:05:40
 */
package com.gestionmatriz.recursoshumanos.gui;

import com.gestionmatriz.dao.PaqueteBusinessDelegate;

import com.gestionmatriz.principal.gui.Principal;
import com.gestionmatriz.recursoshumanos.opciones.Opciones;
import com.gestionmatriz.recursoshumanos.reportes.Ireport;
import com.gestionmatriz.reutilizable.util.Filtro;
import com.gestionmatriz.util.FileChooser;
import com.gestionmatriz.util.Mensaje;
import java.util.List;

/**
 *
 * @author zholo
 */
public class ReportePersona extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form ReportePersona */
    public ReportePersona(Principal gui) {
        this.gui=gui;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboReportes = new org.jdesktop.swingx.JXComboBox();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        cboTrabajador = new org.jdesktop.swingx.JXComboBox();
        btnGenerarReporte = new org.jdesktop.swingx.JXButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("REPORTES POR PERSONAL");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Reportes Por Persona", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        cboReportes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".::Seleccione una opción::.", "Funciones", "Permisos", "Memorandum" }));
        cboReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboReportesActionPerformed(evt);
            }
        });

        jXLabel1.setText("Elegir Reporte");

        jXLabel2.setText("Elegir Trabajador");

        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionmatriz/icon/reportetrabajador.png"))); // NOI18N
        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.setPreferredSize(new java.awt.Dimension(137, 23));
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jXLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        
    
    if(cboTrabajador.getSelectedIndex()<=0){
        Mensaje.mensaje(this, "Debe seleccionar un trabajador",Mensaje.TITULO_ME, Mensaje.ERROR);
        return;
    }
    if(cboReportes.getSelectedIndex()<=0){
        Mensaje.mensaje(this, "Debe seleccionar un Reporte ",Mensaje.TITULO_ME, Mensaje.ERROR);
        return;
    }
    int idPersona=listaPersonal.get(cboTrabajador.getSelectedIndex()-1).getInt_idPersona();
    String strCodigoPersona=listaPersonal.get(cboTrabajador.getSelectedIndex()-1).getStr_codigo();
        if(cboReportes.getSelectedItem().toString().
                        equalsIgnoreCase("Memorandum")){
            if (!Filtro.opcionPermitida(gui.getLstFuncionesUsuario(), Opciones.getREPORTEMEMORANDUM())){
                Mensaje.mensaje(this,"Opción no autorizada para su Usuario", Mensaje.TITULO_ME, Mensaje.ERROR);
                return;
            }
                    ireport.verMemorandumPersona(idPersona,"MemorandumPersona");
        }else if(cboReportes.getSelectedItem().toString().
                        equalsIgnoreCase("Funciones")){
            if (!Filtro.opcionPermitida(gui.getLstFuncionesUsuario(), Opciones.getREPORTEFUNCIONES())){
                Mensaje.mensaje(this,"Opción no autorizada para su Usuario", Mensaje.TITULO_ME, Mensaje.ERROR);
                return;
            }

                if (ireport.verFuncionesXUsuario(strCodigoPersona,"FuncionesUsuario")){
                    Mensaje.mensaje(this,"Reporte generado "
                            , Mensaje.TITULO_ME, Mensaje.INFORMACION);
                }else{
                    Mensaje.mensaje(this,"Error al Generar Reporte", Mensaje.TITULO_ME, Mensaje.ERROR);
                }

        }else{
            if (!Filtro.opcionPermitida(gui.getLstFuncionesUsuario(), Opciones.getREPORTEPERMISOS())){
                Mensaje.mensaje(this,"Opción no autorizada para su Usuario", Mensaje.TITULO_ME, Mensaje.ERROR);
                return;
            }
               ireport.verPermisoPersona(idPersona,"PermisoPersona");
        }
    
}//GEN-LAST:event_btnGenerarReporteActionPerformed

private void cboReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboReportesActionPerformed
    
    if(cboReportes.getSelectedIndex()!=0){
        cargarComboTrabajador();
    }
    
}//GEN-LAST:event_cboReportesActionPerformed

public void cargarComboTrabajador(){
    cboTrabajador.removeAllItems();
            Object objTitle=".::Seleccione un Trabajador::.";

            cboTrabajador.addItem(objTitle);
            
                if(cboReportes.getSelectedItem().toString().
                        equalsIgnoreCase("Memorandum")){
                    listaPersonal=PaqueteBusinessDelegate.
                            getRporteService().listaPersonaMemo();
                }else if(cboReportes.getSelectedItem().toString().
                        equalsIgnoreCase("Funciones")){
                listaPersonal=PaqueteBusinessDelegate.
                            getRporteService().listaPersonalFunciones();
                }else{
                listaPersonal=PaqueteBusinessDelegate.
                            getRporteService().listaPersonalPermisos();
                }
                        
                Object item;
                for (com.gestionmatriz.recursoshumanos.bean.Personal objPersona : listaPersonal) {
                    item=objPersona.getStr_codigo()+" "+objPersona.getStr_apePaterno()+" "+
                            objPersona.getStr_apeMaterno()+" "+objPersona.getStr_nombres();
                    cboTrabajador.addItem(item);
                }            
           
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnGenerarReporte;
    private org.jdesktop.swingx.JXComboBox cboReportes;
    private org.jdesktop.swingx.JXComboBox cboTrabajador;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    // End of variables declaration//GEN-END:variables
    
   private List<com.gestionmatriz.recursoshumanos.bean.Personal>listaPersonal;
   private Principal gui;
   private Ireport ireport= new Ireport();
   
   @Override
    public void dispose() {
//        try {
            gui.getBarraEstado().cerraVentana();
//            setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
//            this.setClosed(true);
//        } catch (PropertyVetoException ex) {
//            log.error("Error al Intentar Cerrar Ventana Persona: "+ex.getMessage());
//        }
    }
}
