/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InfoSystem.java
 *
 * Created on 30-may-2012, 18:03:59
 */
package com.gestionmatriz.principal.gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author YESM
 */
public class InfoSystem extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;



	/** Creates new form InfoSystem */
    public InfoSystem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setFont(new java.awt.Font("Consolas", 1, 11));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    private Image imagen;

   

    public InfoSystem(String nombreImagen) {
        initComponents();
        if (nombreImagen != null) {

            imagen = new ImageIcon(

                           getClass().getResource(nombreImagen)

                           ).getImage();

        }

    }

    public InfoSystem(Image imagenInicial) {

        if (imagenInicial != null) {

            imagen = imagenInicial;

        }
    }

    public void setImagen(String nombreImagen) {

        if (nombreImagen != null) {

            imagen = new ImageIcon(

                   getClass().getResource(nombreImagen)

                   ).getImage();

        } else {

            imagen = null;

        }

 

        repaint();

    }

    public void setImagen(Image nuevaImagen) {

        imagen = nuevaImagen;

 

        repaint();

    }

    @Override
    public void paint(Graphics g) {

        if (imagen != null) {

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),

                              this);

 

            setOpaque(false);

        } else {

            setOpaque(true);

        }
 
        super.paint(g);
    }

    
}
