delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_insertPersonal`(
    IN idPersona int,
    IN cod varchar(45),
    IN paterno varchar(45),
    IN materno varchar(45),
    IN nombres varchar(45),
    IN dni varchar(8),
    IN carnetEstranjeria varchar(15),
    IN fechaNacimiento Date,
    IN ciudadNacimiento varchar(45),
    IN telefono varchar(10),
    IN movil varchar(9),
    IN sexo char(1),
    IN nacionalidad varchar(45),
    IN correoElectronico varchar(45),
    IN brevete char(1),
    IN categoriaBrevete varchar(45),
    IN estadoCivil varchar(15),
    IN direccion varchar(150),
    IN distrito varchar(150),
    IN provincia varchar(150),
    IN departamento varchar(150),
    IN huellaDigital_1 Binary,
    IN huellaDigital_2 Binary,
    IN estado varchar(45),
    IN usuarioCreador varchar(45),
    IN ultimaModificacion Date,
    IN usuarioModificador varchar(45) 
)
BEGIN
    INSERT INTO `matriz`.`tb_persona`
(`int_idPersona`,
`str_codigo`,
`str_apePaterno`,
`str_apeMaterno`,
`str_nombres`,
`str_dni`,
`str_carnetExtranjeria`,
`dte_fechaNacimiento`,
`str_ciudadNacimiento`,
`str_telefono`,
`str_movil`,
`str_sexo`,
`str_nacionalidad`,
`str_correoElectronico`,
`str_brevete`,
`str_categoriaBrevete`,
`str_estadoCivil`,
`str_direccion`,
`str_distrito`,
`str_provincia`,
`str_departamento`,
`bin_huellaDigital_1`,
`bin_huellaDigital_2`,
`str_estado`,
`dte_fechaCreacion`,
`str_usuarioCreador`,
`dte_ultimaModificacion`,
`str_usuarioModificador`)

VALUES
(
idPersona,
cod,
paterno,
materno,
nombres,
dni,
carnetExtranjeria,
fechaNacimiento,
ciudadNacimiento,
telefono,
movil,
sexo,
nacionalidad,
correoElectronico,
brevete,
categoriaBrevete,
estadoCivil,
direccion,
distrito,
provincia,
departamento,
huellaDigital_1,
huellaDigital_2,
estado,
(select now()),
usuarioCreador,
ultimaModificacion,
usuarioModificador

);

END$$
